"use client";

// Mermaid is loaded as a pre-built static script (/mermaid.min.js) rather than
// bundled through webpack — the pure-ESM mermaid 11 package causes ChunkLoadErrors
// when Next.js/webpack tries to bundle it at runtime.

import { useEffect, useId, useRef, useState } from "react";

declare global {
  interface Window {
    mermaid?: {
      initialize: (config: object) => void;
      render: (id: string, text: string) => Promise<{ svg: string }>;
    };
  }
}

let _scriptState: "idle" | "loading" | "ready" | "error" = "idle";
let _scriptCallbacks: Array<(ok: boolean) => void> = [];

function loadMermaidScript(): Promise<boolean> {
  return new Promise((resolve) => {
    if (_scriptState === "ready") { resolve(true); return; }
    if (_scriptState === "error") { resolve(false); return; }

    _scriptCallbacks.push(resolve);

    if (_scriptState === "loading") return;
    _scriptState = "loading";

    const script = document.createElement("script");
    script.src = "/mermaid.min.js";
    script.async = true;

    script.onload = () => {
      _scriptState = "ready";
      window.mermaid?.initialize({
        startOnLoad: false,
        theme: "base",
        themeVariables: {
          primaryColor: "#e8f1ff",
          primaryBorderColor: "#0f5cc0",
          primaryTextColor: "#102031",
          lineColor: "#4e657a",
          secondaryColor: "#eef2f5",
          tertiaryColor: "#f4f6f8",
          fontFamily: "'SF Pro Text', 'Avenir Next', 'Segoe UI', sans-serif",
          fontSize: "14px",
        },
        flowchart: { curve: "basis", padding: 20 },
      });
      _scriptCallbacks.forEach((cb) => cb(true));
      _scriptCallbacks = [];
    };

    script.onerror = () => {
      _scriptState = "error";
      _scriptCallbacks.forEach((cb) => cb(false));
      _scriptCallbacks = [];
    };

    document.head.appendChild(script);
  });
}

interface Props {
  code: string;
}

export function MermaidDiagram({ code }: Props) {
  const uid = useId().replace(/:/g, "m");
  const containerId = `mermaid-${uid}`;
  const containerRef = useRef<HTMLDivElement>(null);
  const [svg, setSvg] = useState<string>("");
  const [error, setError] = useState<string>("");
  const [open, setOpen] = useState(false);

  useEffect(() => {
    let cancelled = false;
    setSvg("");
    setError("");

    loadMermaidScript().then((ok) => {
      if (!ok || cancelled) return;
      if (!window.mermaid) { setError("Mermaid failed to load"); return; }

      window.mermaid
        .render(containerId, code.trim())
        .then(({ svg: rendered }) => { if (!cancelled) setSvg(rendered); })
        .catch((err: unknown) => {
          if (!cancelled) setError(err instanceof Error ? err.message : String(err));
        });
    });

    return () => { cancelled = true; };
  }, [code, containerId]);

  if (error) {
    return (
      <div className="mermaid-error">
        <button
          className="mermaid-error-toggle"
          onClick={() => setOpen((v) => !v)}
          aria-expanded={open}
        >
          ⚠ Diagram syntax error {open ? "▲" : "▼"}
        </button>
        {open && <pre className="mermaid-source">{code}</pre>}
      </div>
    );
  }

  if (!svg) {
    return <div className="mermaid-loading" aria-busy="true">Rendering diagram…</div>;
  }

  return (
    <div
      ref={containerRef}
      className="mermaid-diagram"
      // SVG is generated by the mermaid library from validated diagram syntax
      // eslint-disable-next-line react/no-danger
      dangerouslySetInnerHTML={{ __html: svg }}
      aria-label="Process diagram"
    />
  );
}
