"use client";

import { useEffect, useId, useRef, useState } from "react";

interface Props {
  code: string;
}

let _mermaidReady = false;
let _mermaidInit: Promise<void> | null = null;

async function getMermaid() {
  if (_mermaidReady) return (await import("mermaid")).default;
  if (!_mermaidInit) {
    _mermaidInit = import("mermaid").then((m) => {
      m.default.initialize({
        startOnLoad: false,
        theme: "base",
        themeVariables: {
          primaryColor: "#e8f1ff",
          primaryBorderColor: "#0f5cc0",
          primaryTextColor: "#102031",
          lineColor: "#4e657a",
          secondaryColor: "#eef2f5",
          tertiaryColor: "#f4f6f8",
          fontFamily: "'SF Pro Text', 'Avenir Next', 'Segoe UI', sans-serif",
          fontSize: "14px",
        },
        flowchart: { curve: "basis", padding: 20 },
      });
      _mermaidReady = true;
    });
  }
  await _mermaidInit;
  return (await import("mermaid")).default;
}

export function MermaidDiagram({ code }: Props) {
  const uid = useId().replace(/:/g, "");
  const containerId = `mermaid-${uid}`;
  const containerRef = useRef<HTMLDivElement>(null);
  const [svg, setSvg] = useState<string>("");
  const [error, setError] = useState<string>("");
  const [open, setOpen] = useState(false);

  useEffect(() => {
    let cancelled = false;
    setSvg("");
    setError("");

    getMermaid()
      .then((mermaid) => mermaid.render(containerId, code.trim()))
      .then(({ svg: rendered }) => {
        if (!cancelled) setSvg(rendered);
      })
      .catch((err: unknown) => {
        if (!cancelled) {
          const msg = err instanceof Error ? err.message : String(err);
          setError(msg);
        }
      });

    return () => { cancelled = true; };
  }, [code, containerId]);

  if (error) {
    return (
      <div className="mermaid-error">
        <button
          className="mermaid-error-toggle"
          onClick={() => setOpen((v) => !v)}
          aria-expanded={open}
        >
          ⚠ Diagram syntax error {open ? "▲" : "▼"}
        </button>
        {open && <pre className="mermaid-source">{code}</pre>}
      </div>
    );
  }

  if (!svg) {
    return (
      <div className="mermaid-loading" aria-busy="true">
        Rendering diagram…
      </div>
    );
  }

  return (
    <div
      ref={containerRef}
      className="mermaid-diagram"
      // SVG is generated by the mermaid library — not user-supplied HTML
      // eslint-disable-next-line react/no-danger
      dangerouslySetInnerHTML={{ __html: svg }}
      aria-label="Process diagram"
    />
  );
}
